// GENERATED by tools/local/fixture_gen/gen.py (tool-port pipeline
// Stage 2). Verifier: preview-state. Do not edit by hand — regenerate.
//
// Loop Slice preview-state parity: transient tool state (count / mode / slice positions) read from /api/tool/state after activating on a seed edge.

import fixture_helpers;

void main() {}

unittest {
    enum string json = import("fixtures/loop_slice_preview.json");
    runPreviewStateSuite(json);
}
