// GENERATED by tools/local/fixture_gen/gen.py (tool-port pipeline
// Stage 2). Verifier: topology-diff. Do not edit by hand — regenerate.
//
// Loop Slice topology parity (vibe3d self-golden): vert/edge/face count deltas + per-vertex nearest-match against frozen golden, plus a reference-INDEPENDENT analytic check that every new vertex lies at lerp(edgeA, edgeB, t) of a pre-op edge.

import fixture_helpers;

void main() {}

unittest {
    enum string json = import("fixtures/loop_slice.json");
    runTopologyDiffSuite(json);
}
