// GENERATED by tools/local/fixture_gen/gen.py (tool-port pipeline
// Stage 2). Verifier: rigid-cluster. Do not edit by hand — regenerate.
//
// Reference-parity (frozen capture): a rigid translation of the selected verts, replayed with vibe3d's move tool. Golden verts frozen from a captured gizmo haul; no external tool at test time.

import fixture_helpers;

void main() {}

unittest {
    enum string json = import("fixtures/transform_move.json");
    runParitySuite(json);
}
