// GENERATED by tools/local/fixture_gen/gen.py (tool-port pipeline
// Stage 2). Verifier: topology-diff. Do not edit by hand — regenerate.
//
// Loop-slice topology parity (frozen capture): vert/edge/face count deltas + per-vertex nearest-match against golden verts, plus a reference-INDEPENDENT analytic lerp check. Golden verts frozen from a captured gesture; no external tool at test time.

import fixture_helpers;

void main() {}

unittest {
    enum string json = import("fixtures/loop_slice_ref.json");
    runTopologyDiffSuite(json);
}
