// GENERATED by tools/local/fixture_gen/gen.py from-probe (task
// 0342 Phase 2). Stage: acen. Verifier: runStageAcenSuite. Do not edit by hand —
// regenerate.
//
// ACEN stage-conformance (frozen packet-before-geometry capture): the golden `actionCenter.center` is the reference toolpipe's OWN published ActionCenter packet, read via a passive late-pipe probe during a live haul (zero drift confirmed across every recorded MOVE frame) -- not inferred from post-transform geometry.

import stage_helpers;

void main() {}

unittest {
    enum string json = import("fixtures/stages/probe_acen_select_poly.json");
    runStageAcenSuite(json);
}
