// ACEN stage-conformance suite (task 0342). The FIRST unittest block below
// is GENERATED by tools/local/fixture_gen/gen.py from-probe (Phase 2) —
// do not hand-edit that block, regenerate it instead. Every block AFTER
// the "Phase 3 (hand-authored)" banner is NOT generated — Phase 3 covers
// the idle-eval-equivalent ACEN modes that have no live probe capture to
// generate from (select/local/origin are analytic/probe-mixed; element
// needs a real click-pick, driven directly rather than through a static
// JSON golden — see the per-block comments below and the 0342 task log's
// per-mode disposition for why each mode is/isn't covered here).
//
// ACEN stage-conformance (frozen packet-before-geometry capture): the golden `actionCenter.center` is the reference toolpipe's OWN published ActionCenter packet, read via a passive late-pipe probe during a live haul (zero drift confirmed across every recorded MOVE frame) -- not inferred from post-transform geometry.

import stage_helpers;

void main() {}

// --- GENERATED (gen.py from-probe) --- Mode.Select, real probe capture. ---
unittest {
    enum string json = import("fixtures/stages/probe_acen_select_poly.json");
    runStageAcenSuite(json);
}

// ==========================================================================
// Phase 3 (hand-authored, task 0342) — idle-eval-equivalent ACEN modes that
// don't need a live drag. See doc/tasks/work/0342-stage-conformance-fixtures.md
// Phase 0's per-mode disposition for the reasoning behind each one.
// ==========================================================================

// --- Mode.Local — analytic golden (no live probe for this mode; see the
// fixture's own "source" field for the derivation + live cross-check). ---
unittest {
    enum string json = import("fixtures/stages/acen_local_analytic.json");
    runStageAcenSuite(json);
}

// --- Mode.Origin — trivial constant, selection-independent. ---
unittest {
    enum string json = import("fixtures/stages/acen_origin_analytic.json");
    runStageAcenSuite(json);
}

// --- Mode.Element — LIVE PICK, not a static JSON fixture (review finding
// R3): driving this mode through the generic mesh_build/selection/pipe_setup
// vocabulary (e.g. writing userPlacedCenter via tool.pipe.attr) only reaches
// the userPin FALLBACK tier of computeCenter's Element arm, never the actual
// live-element tier (liveElementCenter()) that a real click-pick populates
// (XfrmTransformTool.tryPickElement -> takeFace -> notifyAcenElementVerts).
// Asserting the fallback tier and calling it "element parity" would be a
// false green. runStageAcenElementLivePick fires a REAL play-events click
// (off-centre, so the click point provably differs from the face centroid)
// and asserts BOTH that the result equals the picked face's own centroid
// AND that it does NOT equal the click point — see tests/stage_helpers.d
// for the full rationale and the mechanism.
unittest {
    runStageAcenElementLivePick();
}
