// GENERATED by tools/local/fixture_gen/gen.py (tool-port pipeline
// Stage 2). Verifier: attr-echo. Do not edit by hand — regenerate.
//
// Loop Slice attr-echo parity: the Position attr echoes in tool state and derives a slice vertex at the implied parameter along the ring rails.

import fixture_helpers;

void main() {}

unittest {
    enum string json = import("fixtures/loop_slice_attr.json");
    runAttrEchoSuite(json);
}
