module tests.unit.ui.action_menu_roles_test;

import std.algorithm : count;
import std.file : SpanMode, dirEntries, readText;
import std.json : parseJSON;
import std.path : buildNormalizedPath, buildPath, dirName;
import std.string : indexOf;

import application_command_binding : ApplicationCommandBinding;
import bindbc.sdl : SDL_Keymod, KMOD_ALT, KMOD_CTRL, KMOD_GUI, KMOD_NONE,
    KMOD_SHIFT;
import buttonset : Action, ActionKind, Button, Panel, PopupItem, PopupItemKind,
    loadButtons;
import command : CmdFlags, Command, g_testMode;
import command_executor : CommandExecutor;
import command_history : CommandHistory, RecordMode;
import edit_session : EditSession;
import editmode : EditMode;
import guarded_action_controller : GuardObservationPorts,
    GuardedActionController, GuardedActionPorts;
import mesh : makeCube;
import params : Param;
import registry : Registry;
import session_owner : Session;
import tests.unit.ui.headless_panel : openPanel;
import tool : Tool;
import tool_activation_ownership : ToolTransition;
import toolpipe.packets : FalloffType;
import toolpipe.pipeline : g_pipeCtx, ToolPipeContext;
import toolpipe.stage : TaskCode;
import toolpipe.stages.falloff : FalloffStage;
import ui.action_menu : ActionMenuRoles, bindActionMenu, dispatchAction,
    popupWidgetId, renderButtonPopups, renderFalloffStackItems,
    renderPopupItems, selectButtonVariant;
import ui.availability : beginButtonAvailabilityFrame,
    buttonAvailabilityJson, endButtonAvailabilityFrame;
import view : View;
import ImGui = d_imgui;
static import ui.action_menu;

// Generated by compiling a temporary
// `pragma(msg, [__traits(allMembers, ui.action_menu)]);` in the production
// module, then copying its emitted literal and removing the pragma.
static assert([__traits(allMembers, ui.action_menu)] == [
    "object", "ImGui", "ActionMenuDispatch", "ActionMenuToolActivate",
    "ActionMenuArgsDialog", "ActionMenuRefusal", "ActionMenuRead",
    "ActionMenuActions", "ActionMenuRoles", "bindActionMenu",
    "dispatchAction", "renderFalloffStackItems", "renderDynamicPopupItems",
    "renderPopupItems", "renderVariantPopup", "renderButtonPopups",
    "popupWidgetId", "selectButtonVariant", "popupItemChecked",
    "popupActionNeedsAssimp", "firstCheckedLabel"
], "6560 action-menu module member set changed — a new member was born beside the roles");

static assert([__traits(allMembers, ui.action_menu.ActionMenuRead)]
    == ["refusal_", "__ctor", "refusal"],
    "6560 ActionMenuRead member set changed — the read role gained a capability");
static assert([__traits(allMembers, ui.action_menu.ActionMenuActions)]
    == ["activateTool_", "openArgs_", "dispatch_", "__ctor",
        "activateTool", "runCommandRow", "runScriptLine"],
    "6560 ActionMenuActions member set changed — the action role gained a door");
static assert([__traits(allMembers, ui.action_menu.ActionMenuRoles)]
    == ["read", "actions"],
    "6560 ActionMenuRoles member set changed");

static assert(!__traits(compiles, {
    ActionMenuRoles roles = void;
    roles.actions.dispatch_ = (string id, string paramsJson) {};
}), "6560 cross-module half: an outside module must not replace the dispatch door");
static assert(!__traits(compiles, new ui.action_menu.ActionMenuRead()),
    "6560 only bindActionMenu may build a read role");
static assert(__traits(compiles, (ui.action_menu.ActionMenuActions actions) {
    actions.activateTool("x");
    actions.runCommandRow("y");
}), "6560 anti-vacuity: the action role stopped compiling, so every negative above went green");

private enum repoRoot = buildNormalizedPath(
    dirName(__FILE_FULL_PATH__), "..", "..", "..");

private final class MenuProbeState {
    size_t applies;
    float lastAmount;
}

private final class MenuProbeCommand : Command {
    private string id_;
    private MenuProbeState state_;
    private bool applies_;
    private bool parameterized_;
    private float amount_;

    this(Session* owner, ref View view, string id, MenuProbeState state,
         bool applies = true, bool parameterized = false) {
        super(&owner.editMesh(), view, owner.editMode);
        id_ = id;
        state_ = state;
        applies_ = applies;
        parameterized_ = parameterized;
    }

    override string name() const { return id_; }
    override string label() const { return "Action-menu " ~ id_; }
    override CmdFlags cmdFlags() const { return CmdFlags.Model; }
    override Param[] params() {
        return parameterized_
            ? [Param.float_("amount", "Amount", &amount_, 0.0f)]
            : [];
    }
    protected override bool applyImpl() {
        if (!applies_) {
            baseRefusal_ = "action-menu refusal";
            return false;
        }
        ++state_.applies;
        state_.lastAmount = amount_;
        noteUndoRecorded();
        return true;
    }
    protected override void revertImpl() {}
}

private final class ActionMenuHarness {
    Session* owner;
    View view;
    Registry registry;
    CommandHistory history;
    CommandExecutor executor;
    EditSession editSession;
    GuardedActionController guard;
    ApplicationCommandBinding binding;
    Tool activeTool;
    MenuProbeState state;
    size_t guardNoticeCount;
    string lastGuardNotice;
    size_t dispatchCount;
    size_t openArgsCount;
    size_t activationCount;

    this() {
        owner = Session.bootstrap(makeCube());
        view = new View(0, 0, 800, 600);
        history = new CommandHistory;
        executor = new CommandExecutor(history,
            () => activeTool !is null,
            (ToolTransition) { activeTool = null; });
        editSession = new EditSession(
            () => activeTool, history, () { activeTool = null; });
        guard = new GuardedActionController(GuardedActionPorts(
            (Command command, RecordMode mode) =>
                executor.applyOrRefire(command, mode, null),
            () => false,
            () => true,
            (Command command) {
                ++guardNoticeCount;
                lastGuardNotice = command.name();
            },
            GuardObservationPorts(
                (record) {}, (answer, performed) {}, (pending) {})));
        binding = new ApplicationCommandBinding(
            registry, executor, editSession, history, guard,
            (Command) {}, (string) {});
        state = new MenuProbeState;
        registry.registerCommand("probe.script", () => cast(Command)
            new MenuProbeCommand(owner, view, "probe.script", state, true, true));
        registry.registerCommand("probe.command", () => cast(Command)
            new MenuProbeCommand(owner, view, "probe.command", state));
        registry.registerCommand("probe.refuse", () => cast(Command)
            new MenuProbeCommand(owner, view, "probe.refuse", state, false));
        registry.registerCommand("probe.args", () => cast(Command)
            new MenuProbeCommand(owner, view, "probe.args", state, true, true));
    }

    ActionMenuRoles bind(bool openParameterized = false) {
        return bindActionMenu(
            (ref const Action action) => "",
            (string id, string paramsJson) {
                ++dispatchCount;
                binding.dispatchUi(id, paramsJson);
            },
            (string) { ++activationCount; },
            (string id) {
                ++openArgsCount;
                return openParameterized && id == "probe.args";
            });
    }

    void clear() {
        history.clear();
        state.applies = 0;
        state.lastAmount = 0;
        guardNoticeCount = 0;
        lastGuardNotice = "";
        dispatchCount = 0;
        openArgsCount = 0;
        activationCount = 0;
        assert(history.undoEntries().length == 0,
            "6560 history floor must begin below the capped-stack boundary");
    }
}

private Action scriptAction(string[] lines) {
    Action action;
    action.kind = ActionKind.script;
    action.scriptLines = lines;
    return action;
}

private Action commandAction(string id) {
    Action action;
    action.kind = ActionKind.command;
    action.id = id;
    return action;
}

private PopupItem[] firstRealPopup() {
    Panel[] panels = loadButtons("config/buttons.yaml");
    PopupItem[] rows;
    foreach (ref panel; panels)
        foreach (ref item; panel.items) {
            if (item.isGroup) {
                foreach (ref button; item.group.buttons)
                    if (button.action.kind == ActionKind.popup
                        && button.action.popupItems.length >= 2) {
                        rows ~= button.action.popupItems;
                        if (rows.length >= 8) return rows;
                    }
            } else if (item.button.action.kind == ActionKind.popup
                    && item.button.action.popupItems.length >= 2) {
                rows ~= item.button.action.popupItems;
                if (rows.length >= 8) return rows;
            }
        }
    return rows;
}

unittest { // C1: the production binder builds both roles over non-empty floors
    auto h = new ActionMenuHarness;
    auto roles = h.bind();
    auto floorAction = commandAction("probe.command");
    assert(roles.read.refusal(floorAction).length == 0,
        "6560 role floor: the production binder did not construct its read role");
    roles.actions.activateTool("probe.tool");
    assert(h.activationCount == 1,
        "6560 role floor: the production binder did not construct its action role");
    assert(h.history.undoEntries().length == 0,
        "6560 binder floor: construction must not write history");
}

private Button penButton() {
    Button b;
    b.label  = "Pen";
    b.action = Action(ActionKind.tool, "pen");
    b.ctrl.present = true;
    b.ctrl.label   = "Topology Pen";
    b.ctrl.action  = Action(ActionKind.tool, "mesh.topoPen");
    return b;
}

unittest { // C2a: the six relocated variant cells
    string label;
    Action action;
    string variant;
    auto btn = penButton();

    assert(btn.ctrl.present, "6560 variant floor: the ctrl fixture is absent");
    selectButtonVariant(btn, KMOD_CTRL, "", label, action, variant);
    assert(action.id == "mesh.topoPen" && label == "Topology Pen" && variant == "_ctrl");

    assert(btn.ctrl.present, "6560 variant floor: the ctrl fixture is absent");
    selectButtonVariant(btn, KMOD_NONE, "mesh.topoPen", label, action, variant);
    assert(action.id == "mesh.topoPen", "released modifier must not drop an active variant tool");
    assert(label == "Topology Pen", "an active variant must keep its own label");

    assert(btn.ctrl.present, "6560 variant floor: the ctrl fixture is absent");
    selectButtonVariant(btn, KMOD_NONE, "pen", label, action, variant);
    assert(action.id == "pen" && label == "Pen" && variant == "");

    assert(btn.ctrl.present, "6560 variant floor: the ctrl fixture is absent");
    selectButtonVariant(btn, KMOD_NONE, "", label, action, variant);
    assert(action.id == "pen" && variant == "");

    assert(btn.ctrl.present, "6560 variant floor: the ctrl fixture is absent");
    version (OSX) {
        selectButtonVariant(btn, KMOD_GUI, "", label, action, variant);
        assert(action.id == "mesh.topoPen", "macOS: Cmd must reach a ctrl: variant");
        selectButtonVariant(btn, KMOD_CTRL, "", label, action, variant);
        assert(action.id == "pen" && label == "Pen", "macOS: Control must not preview a variant it cannot click");
    } else {
        selectButtonVariant(btn, KMOD_GUI, "", label, action, variant);
        assert(action.id == "pen", "non-macOS: Super/Cmd must NOT alias Ctrl");
        selectButtonVariant(btn, KMOD_CTRL, "", label, action, variant);
        assert(action.id == "mesh.topoPen", "non-macOS: Control selects the ctrl: variant");
    }

    Button cmdBtn;
    cmdBtn.label  = "Arc";
    cmdBtn.action = Action(ActionKind.tool, "prim.arc");
    cmdBtn.ctrl.present = true;
    cmdBtn.ctrl.label   = "Unit Arc";
    cmdBtn.ctrl.action  = Action(ActionKind.command, "prim.arc.unit");
    assert(cmdBtn.ctrl.present, "6560 variant floor: the command ctrl fixture is absent");
    selectButtonVariant(cmdBtn, KMOD_NONE, "prim.arc", label, action, variant);
    assert(action.id == "prim.arc" && variant == "", "a command variant must not claim the button");
}

unittest { // C2b: simultaneous held modifiers keep Ctrl above Alt
    string label;
    Action action;
    string variant;
    auto btn = penButton();
    btn.alt.present = true;
    btn.alt.label = "Alt Pen";
    btn.alt.action = Action(ActionKind.tool, "mesh.altPen");
    btn.shift.present = true;
    btn.shift.label = "Shift Pen";
    btn.shift.action = Action(ActionKind.tool, "mesh.shiftPen");
    assert(btn.ctrl.present && btn.alt.present && btn.shift.present,
        "6560 modifier-priority floor: all three variants must exist");
    version (OSX) enum testCtrl = KMOD_GUI;
    else          enum testCtrl = KMOD_CTRL;
    immutable heldMods = cast(SDL_Keymod)(testCtrl | KMOD_ALT | KMOD_SHIFT);
    assert((heldMods & testCtrl) != 0 && (heldMods & KMOD_ALT) != 0
        && (heldMods & KMOD_SHIFT) != 0,
        "6560 modifier-priority floor: ctrl, alt, and shift must all be held");
    selectButtonVariant(btn, heldMods, "", label, action, variant);
    assert(variant == "_ctrl",
        "6560 modifier priority: ctrl must win over simultaneously held alt and shift");
}

unittest { // C2c: active variant claims retain Ctrl-before-Alt ordering
    string label;
    Action action;
    string variant;
    auto btn = penButton();
    btn.ctrl.action = Action(ActionKind.tool, "mesh.sharedPen");
    btn.alt.present = true;
    btn.alt.label = "Alt Shared Pen";
    btn.alt.action = Action(ActionKind.tool, "mesh.sharedPen");
    btn.shift.present = true;
    btn.shift.label = "Shift Shared Pen";
    btn.shift.action = Action(ActionKind.tool, "mesh.sharedPen");
    immutable activeToolId = "mesh.sharedPen";
    assert(btn.ctrl.present && btn.alt.present && btn.shift.present
        && activeToolId.length > 0,
        "6560 active-variant floor: all variants and an active id must exist");
    selectButtonVariant(btn, KMOD_NONE, activeToolId, label, action, variant);
    assert(label == btn.ctrl.label,
        "6560 active variant priority: ctrl must claim before alt when both name the active tool");
    btn.ctrl.action = Action(ActionKind.tool, "mesh.ctrlOnlyPen");
    selectButtonVariant(btn, KMOD_NONE, activeToolId, label, action, variant);
    assert(label == btn.alt.label && variant == "_alt",
        "6560 active variant priority: alt must claim before shift when both name the active tool");

    btn.ctrl.action = Action(ActionKind.tool, "");
    btn.alt.action = Action(ActionKind.tool, "mesh.altPen");
    btn.shift.action = Action(ActionKind.tool, "mesh.shiftPen");
    selectButtonVariant(btn, KMOD_NONE, "", label, action, variant);
    assert(action.id == "pen" && variant.length == 0,
        "6560 active variant guard: an empty tool id must not claim an idle button");
}

unittest { // C3: a modifier popup id remains addressable after modifier release
    const savedTestMode = g_testMode;
    g_testMode = true;
    scope (exit) g_testMode = savedTestMode;
    auto h = new ActionMenuHarness;
    auto roles = h.bind();
    Button btn;
    btn.label = "Variant host";
    btn.action = commandAction("probe.command");
    btn.alt.present = true;
    btn.alt.label = "Variant popup";
    btn.alt.action.kind = ActionKind.popup;
    foreach (i; 0 .. 2) {
        PopupItem row;
        row.kind = PopupItemKind.action;
        row.label = "Popup row" ~ cast(char)('A' + i);
        row.action = commandAction("probe.command");
        btn.alt.action.popupItems ~= row;
    }
    assert(btn.alt.action.popupItems.length >= 2,
        "6560 popup-id floor: the alternate popup needs two submitted rows");
    assert(popupWidgetId(btn.label, "") != popupWidgetId(btn.label, "_alt"),
        "6560 popup ids: primary and alternate popup ids must stay distinct");
    bool opened;
    auto ui = openPanel(() {
        beginButtonAvailabilityFrame(true, "", 0);
        scope (exit) endButtonAvailabilityFrame();
        if (!opened) {
            ImGui.OpenPopup(popupWidgetId(btn.label, "_alt"));
            opened = true;
        }
        renderButtonPopups(btn, roles.read, roles.actions);
    }, "action menu modifier host");
    scope (exit) ui.close();
    ui.frame();
    auto rows = parseJSON(buttonAvailabilityJson())["buttons"].array;
    assert(rows.length > 0,
        "6560 instrument floor: the drawn-button record is empty — g_testMode or the availability bracket was not raised");
    size_t publishedPopupRows;
    foreach (row; rows)
        if (row["source"].str == "popup") ++publishedPopupRows;
    assert(publishedPopupRows >= 2,
        "6560 popup id: releasing Alt must not orphan the alternate popup rows");
}

unittest { // C4: real YAML popup rows publish enabled and refused availability
    const savedTestMode = g_testMode;
    g_testMode = true;
    scope (exit) g_testMode = savedTestMode;
    auto h = new ActionMenuHarness;
    PopupItem[] rows = firstRealPopup();
    assert(rows.length >= 8,
        "6560 real-popup floor: config/buttons.yaml yielded fewer than both file popups");
    string refusedId;
    foreach (ref row; rows)
        if (row.kind == PopupItemKind.action
            && row.action.kind == ActionKind.command) {
            refusedId = row.action.id;
            break;
        }
    assert(refusedId.length > 0,
        "6560 real-popup floor: no command row can carry a refusal");
    immutable refusalSentence = "blocked by the action-menu registry probe";
    auto roles = bindActionMenu(
        (ref const Action action) => action.id == refusedId
            ? refusalSentence : "",
        (string id, string paramsJson) {}, (string id) {},
        (string id) => false);
    auto ui = openPanel(() {
        beginButtonAvailabilityFrame(true, "", 0);
        scope (exit) endButtonAvailabilityFrame();
        renderPopupItems(roles.read, roles.actions, rows);
    }, "action menu availability host");
    scope (exit) ui.close();
    ui.frame();
    auto recorded = parseJSON(buttonAvailabilityJson())["buttons"].array;
    assert(recorded.length > 0,
        "6560 instrument floor: the drawn-button record is empty — g_testMode or the availability bracket was not raised");
    size_t disabled, enabled;
    bool reasonSeen;
    foreach (row; recorded) {
        if (row["source"].str != "popup") continue;
        if (row["disabled"].boolean) {
            ++disabled;
            if (row["reason"].str == refusalSentence) reasonSeen = true;
        } else {
            ++enabled;
        }
    }
    assert(disabled >= 1 && enabled >= 1,
        "6560 popup availability: the real table must publish both disabled and enabled rows");
    assert(reasonSeen,
        "6560 popup availability: the refused row lost the registry sentence");
}

unittest { // C5: script arguments travel through the UI binding into history
    auto h = new ActionMenuHarness;
    auto roles = h.bind();
    h.clear();
    auto action = scriptAction(["probe.script amount:2.5"]);
    assert(h.history.undoEntries().length == 0,
        "6560 script dispatch floor: history was not empty before dispatch");
    dispatchAction(roles.actions, action);
    assert(h.state.applies == 1 && h.state.lastAmount == 2.5f,
        "6560 script dispatch: parsed arguments did not reach the registered command");
    assert(h.history.undoEntries().length == 1,
        "6560 script dispatch: a script line with arguments must run through the UI command binding and record one history entry");
}

unittest { // C5b: the command branch also enters through the UI binding
    auto h = new ActionMenuHarness;
    auto roles = h.bind();
    h.clear();
    auto action = commandAction("probe.command");
    assert(h.history.undoEntries().length == 0,
        "6560 command-row floor: history was not empty before dispatch");
    dispatchAction(roles.actions, action);
    assert(h.history.undoEntries().length == 1,
        "6560 command row: a registered non-refusing command must record exactly one history entry through the UI door");
    assert(h.openArgsCount == 1,
        "6560 command row: the args-dialog policy must be asked exactly once");
}

unittest { // C6: blank and comment script lines do not manufacture commands
    auto h = new ActionMenuHarness;
    auto roles = h.bind();
    h.clear();
    auto action = scriptAction(["probe.script amount:3.5", "", "# skipped"]);
    assert(action.scriptLines.length == 3,
        "6560 empty-line floor: the fixture must contain command, blank, and comment lines");
    dispatchAction(roles.actions, action);
    assert(h.state.applies == 1 && h.state.lastAmount == 3.5f,
        "6560 script empty lines: only the non-empty command may apply");
    assert(h.history.undoEntries().length == 1,
        "6560 script empty lines: blank and comment lines must not create history entries");
}

unittest { // C7: ordinary UI refusal reports through the guard notice port
    auto h = new ActionMenuHarness;
    auto roles = h.bind();
    h.clear();
    auto action = commandAction("probe.refuse");
    assert(h.guardNoticeCount == 0,
        "6560 UI-refusal floor: the guard notice port was already dirty");
    bool threw;
    try {
        dispatchAction(roles.actions, action);
    } catch (Exception) {
        threw = true;
    }
    assert(!threw,
        "6560 UI refusal: an ordinary command refusal must notify, not throw");
    assert(h.guardNoticeCount == 1 && h.lastGuardNotice == "probe.refuse",
        "6560 UI refusal: the guarded-action notice port must record the refused command exactly once");
    assert(h.history.undoEntries().length == 0,
        "6560 UI refusal: a refused command must not change history");
    // Script-origin HTTP refusal is intentionally a different contract: its
    // CommandHttpAdapter door throws, while this UI door records a notice.
}

unittest { // C8: parameterized command rows stop at the args dialog
    auto h = new ActionMenuHarness;
    auto roles = h.bind(true);
    h.clear();
    auto action = commandAction("probe.args");
    assert(h.dispatchCount == 0,
        "6560 args-dialog floor: dispatch count changed before the row ran");
    dispatchAction(roles.actions, action);
    assert(h.openArgsCount == 1 && h.dispatchCount == 0,
        "6560 args dialog: a command row with parameters must open the dialog instead of dispatching with empty arguments");
    assert(h.history.undoEntries().length == 0,
        "6560 args dialog: opening the dialog must not write history");
}

unittest { // C9/C10: real rows carry production commands and remove one extra
    const savedTestMode = g_testMode;
    g_testMode = true;
    scope (exit) g_testMode = savedTestMode;
    auto savedPipe = g_pipeCtx;
    scope (exit) g_pipeCtx = savedPipe;
    auto context = new ToolPipeContext;
    auto primary = new FalloffStage(null, null, "falloff");
    auto extra1 = new FalloffStage(null, null, "falloff#1");
    auto extra2 = new FalloffStage(null, null, "falloff#2");
    context.pipeline.add(primary);
    context.pipeline.addStacked(extra1);
    context.pipeline.addStacked(extra2);
    primary.type = FalloffType.Linear;
    extra1.type = FalloffType.Radial;
    extra2.type = FalloffType.None;
    g_pipeCtx = context;
    assert(context.pipeline.findAllByTask(TaskCode.Wght).length == 3,
        "6560 falloff popup floor: the real pipeline must contain primary plus two extras");
    auto roles = bindActionMenu(
        (ref const Action) => "",
        (string id, string paramsJson) {
            if (id != "falloff.remove") return;
            import command_args : firstPositionalString;
            import std.json : parseJSON;
            auto params = parseJSON(paramsJson);
            const target = firstPositionalString(params);
            auto stage = context.pipeline.findById(target);
            if (stage !is null) context.pipeline.removeStage(stage);
        },
        (string) {}, (string) => false);
    auto ui = openPanel(() {
        beginButtonAvailabilityFrame(true, "", 0);
        scope (exit) endButtonAvailabilityFrame();
        renderFalloffStackItems(roles.actions);
    },
        "action menu falloff host");
    scope (exit) ui.close();
    ui.frame();
    auto activeRows = parseJSON(buttonAvailabilityJson())["buttons"].array;
    assert(activeRows.length == 3,
        "6560 falloff rows: active primary plus two stacked falloffs must be drawn");
    string removeLine;
    bool resetLineSeen, secondRemoveSeen;
    foreach (row; activeRows) {
        assert(row["source"].str == "popup" && row["kind"].str == "script"
            && !row["disabled"].boolean && row["reason"].str.length == 0,
            "6560 falloff rows: every recorded row must be an enabled popup script action");
        const id = row["id"].str;
        if (id == "tool.pipe.attr falloff type none") resetLineSeen = true;
        if (id == "falloff.remove falloff#1") removeLine = id;
        if (id == "falloff.remove falloff#2") secondRemoveSeen = true;
    }
    assert(resetLineSeen && removeLine.length > 0 && secondRemoveSeen,
        "6560 falloff commands: drawn rows must carry both production command forms");

    primary.type = FalloffType.None;
    ui.frame();
    auto inactiveRows = parseJSON(buttonAvailabilityJson())["buttons"].array;
    assert(inactiveRows.length == 2,
        "6560 inactive primary: only the two stacked falloffs may be drawn");
    foreach (row; inactiveRows)
        assert(row["id"].str != "tool.pipe.attr falloff type none",
            "6560 inactive primary: the none-typed primary must stay hidden");

    immutable before = context.pipeline.findAllByTask(TaskCode.Wght).length;
    assert(before == 3,
        "6560 falloff click floor: the stack changed before the gesture");
    // MenuItem row 1 is not hover-addressable through the DragFloat-oriented
    // HeadlessPanel pitch, so dispatch the exact command recorded by the real
    // production row above rather than copying its literal into the fixture.
    auto remove = scriptAction([removeLine]);
    dispatchAction(roles.actions, remove);
    ui.frame();
    assert(context.pipeline.findById("falloff#1") is null,
        "6560 falloff click: the second popup row must remove falloff#1");
    assert(context.pipeline.findById("falloff") is primary,
        "6560 falloff click: removing a stacked extra must retain primary falloff");
}

private string bodyAt(string code, string marker) {
    const at = code.indexOf(marker);
    assert(at >= 0, "6560 census missing source marker " ~ marker);
    size_t i = cast(size_t)at;
    while (i < code.length && code[i] != '{') ++i;
    assert(i < code.length, "6560 census found no body after " ~ marker);
    const begin = i;
    size_t depth;
    for (; i < code.length; ++i) {
        if (code[i] == '{') ++depth;
        else if (code[i] == '}' && --depth == 0)
            return code[begin .. i + 1];
    }
    assert(false, "6560 census found unterminated body after " ~ marker);
    return null;
}

private bool identifierChar(char ch) {
    return ch == '_' || (ch >= '0' && ch <= '9')
        || (ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z');
}

private size_t identifierCount(string code, string identifier) {
    size_t total;
    size_t from;
    while (from < code.length) {
        const hit = code.indexOf(identifier, from);
        if (hit < 0) break;
        const pos = cast(size_t)hit;
        const left = pos == 0 || !identifierChar(code[pos - 1]);
        const end = pos + identifier.length;
        const right = end == code.length || !identifierChar(code[end]);
        if (left && right) ++total;
        from = end;
    }
    return total;
}

private string collapseWhitespace(string source) {
    string result;
    bool spacing;
    foreach (ch; source) {
        const whitespace = ch == ' ' || ch == '\n' || ch == '\r' || ch == '\t';
        if (whitespace) {
            spacing = result.length > 0;
            continue;
        }
        if (spacing) result ~= ' ';
        result ~= ch;
        spacing = false;
    }
    return result;
}

unittest { // C11: status bar owns one role dispatch and one tool drop
    import tests.unit.census_symbols : blankNonCode;

    const panels = blankNonCode(readText(
        repoRoot.buildPath("source", "ui", "panels.d")));
    const body = bodyAt(panels,
        "void drawStatusBar(EditorApp app, ActionMenuRoles menu)");
    assert(body.length > 4_000,
        "6560 status census floor: drawStatusBar body is unexpectedly small");
    assert(body.count("dispatchAction(menu.actions, action)") == 1,
        "6560 status dispatch: drawStatusBar must use the shared action door exactly once");
    const flatBody = collapseWhitespace(body);
    assert(flatBody.count(
            "if (action.kind == ActionKind.popup) { ImGui.OpenPopup(popupId); } else { dispatchAction(menu.actions, action);") == 1,
        "6560 status popup branch: popup actions must open instead of dispatching and dropping the tool");
    assert(body.count("dropActiveTool(ToolTransition.panelDrop)") == 1,
        "6560 status drop: edit-mode actions must retain one post-dispatch tool drop");
    assert(body.count("tryOpenArgsDialog") == 0
        && body.count("uiCommandDelegate") == 0
        && body.count("activateToolById") == 0,
        "6560 status boundary: drawStatusBar regained an application action door");
}

unittest { // C12: side panel consumes the shared dispatch and popup renderer
    import tests.unit.census_symbols : blankNonCode;

    const panels = blankNonCode(readText(
        repoRoot.buildPath("source", "ui", "panels.d")));
    const body = bodyAt(panels,
        "void drawSidePanel(EditorApp app, ActionMenuRoles menu)");
    assert(body.length > 3_000,
        "6560 side census floor: drawSidePanel body is unexpectedly small");
    assert(body.count("dispatchAction(menu.actions, action)") == 1,
        "6560 side dispatch: drawSidePanel must use the shared action door exactly once");
    assert(body.count(
            "renderButtonPopups(btn, menu.read, menu.actions)") == 1,
        "6560 side popup: drawSidePanel must submit the shared popup renderer exactly once");
    assert(body.count("renderVariantPopup") == 0,
        "6560 side boundary: the old nested popup renderer returned");
}

unittest { // C13: production boundary, wiring, and private-reachability census
    import tests.unit.census_symbols : blankNonCode;

    const rawActionMenu = readText(
        repoRoot.buildPath("source", "ui", "action_menu.d"));
    const rawPanels = readText(repoRoot.buildPath("source", "ui", "panels.d"));
    const rawApp = readText(repoRoot.buildPath("source", "app.d"));
    const rawRouter = readText(repoRoot.buildPath("source", "input_router.d"));
    const actionMenu = blankNonCode(rawActionMenu);
    const panels = blankNonCode(rawPanels);
    const app = blankNonCode(rawApp);
    const router = blankNonCode(rawRouter);
    assert(rawActionMenu.length > 6_000,
        "6560 source population: ui/action_menu.d is unexpectedly small");

    assert(identifierCount(actionMenu, "EditorApp") == 0,
        "6560 action-menu boundary: ui/action_menu.d must not name EditorApp — the whole-app channel is what this slice removed");
    assert(actionMenu.count("editor_app") == 0
        && actionMenu.count("with (") == 0
        && identifierCount(actionMenu, "Mesh") == 0
        && identifierCount(actionMenu, "mesh") == 0
        && identifierCount(actionMenu, "CommandHistory") == 0
        && identifierCount(actionMenu, "history") == 0
        && actionMenu.count("ai3d") == 0
        && identifierCount(actionMenu, "Modal") == 0
        && identifierCount(actionMenu, "Registry") == 0
        && identifierCount(actionMenu, "actionRefusal") == 0
        && identifierCount(actionMenu, "Session") == 0
        && identifierCount(actionMenu, "Document") == 0
        && identifierCount(actionMenu, "kCopilotEnabled") == 0,
        "6560 action-menu boundary: the module regained an application-owned type or policy");
    assert(identifierCount(actionMenu, "ApplicationCommandBinding") == 0
        && identifierCount(actionMenu, "dispatchUi") == 0,
        "6560 action-menu dispatch boundary: the module must depend on the narrow delegate, not its app binding");

    assert(identifierCount(actionMenu, "refusal_") == 3,
        "6560 private reachability: refusal_ references grew or its guard path disappeared");
    assert(identifierCount(actionMenu, "activateTool_") == 4,
        "6560 private reachability: activateTool_ references grew or its null guard disappeared");
    assert(identifierCount(actionMenu, "openArgs_") == 4,
        "6560 private reachability: openArgs_ references grew or its null guard disappeared");
    assert(identifierCount(actionMenu, "dispatch_") == 6,
        "6560 private reachability: dispatch_ references grew or a null guard disappeared");
    assert(actionMenu.count("actions.activateTool(") >= 1
        && actionMenu.count("actions.runCommandRow(") == 1
        && actionMenu.count("actions.runScriptLine(") == 1
        && actionMenu.count("read.refusal(") == 1,
        "6560 role use census: production bypassed or duplicated a public role method");

    const binder = bodyAt(actionMenu,
        "ActionMenuRoles bindActionMenu(ActionMenuRefusal refusal,");
    assert(binder.length > 100,
        "6560 binder floor: bindActionMenu body is unexpectedly small");
    assert(binder.count("ActionMenuRead(refusal)") == 1
        && binder.count(
            "ActionMenuActions(activateTool, openArgs, dispatch)") == 1
        && identifierCount(binder, "assert") == 4,
        "6560 binder census: all four doors must be asserted and assigned once");

    const flatActionMenu = collapseWhitespace(actionMenu);
    assert(flatActionMenu.count(
            "void dispatchAction(ActionMenuActions actions, ref Action action)") == 1
        && flatActionMenu.count(
            "void renderPopupItems(ActionMenuRead read, ActionMenuActions actions, ref PopupItem[] items)") == 1
        && flatActionMenu.count(
            "void renderFalloffStackItems(ActionMenuActions actions)") == 1,
        "6560 action-menu signatures: the three narrow entry points changed");

    const falloff = bodyAt(actionMenu,
        "void renderFalloffStackItems(ActionMenuActions actions)");
    assert(falloff.length > 400,
        "6560 falloff census floor: renderFalloffStackItems body is unexpectedly small");
    const loopMarker =
        "foreach (stage; g_pipeCtx.pipeline.findAllByTask(TaskCode.Wght))";
    const loopAt = falloff.indexOf(loopMarker);
    const loopBody = bodyAt(falloff, loopMarker);
    const loopBodyAt = falloff.indexOf(loopBody);
    const loopEnd = loopBodyAt < 0 ? -1L
        : loopBodyAt + cast(long)loopBody.length;
    const dispatchAt = falloff.indexOf("dispatchAction(actions, action)");
    assert(loopAt >= 0 && loopEnd >= 0 && dispatchAt > loopEnd,
        "6560 deferred falloff remove: the stack dispatch must sit after the findAllByTask walk, not inside it");
    assert(identifierCount(falloff, "pending") == 4
        && falloff.count("pending = commandLine;") == 1
        && falloff.count("actions.runScriptLine") == 0
        && falloff.count("dispatchAction(actions, action)") == 1,
        "6560 deferred falloff remove: pending or shared-dispatch structure changed");

    const variantPopup = bodyAt(actionMenu,
        "void renderVariantPopup(string buttonLabel, string variantSuffix, ref Action action,");
    assert(variantPopup.count(
            "if (action.kind != ActionKind.popup) return;") == 1,
        "6560 popup-kind guard: a non-popup action must not enter the popup renderer");

    assert(panels.count("void dispatchAction(EditorApp") == 0
        && panels.count("void renderPopupItems(EditorApp") == 0
        && panels.count("void renderFalloffStackItems(EditorApp") == 0
        && panels.count("void renderDynamicPopupItems(EditorApp") == 0
        && panels.count("dispatchAction(app,") == 0
        && panels.count("renderPopupItems(app,") == 0,
        "6560 panels boundary: a removed whole-app action helper returned");
    assert(router.count("dispatchAction(app,") == 0
        && router.count("import ui.panels") == 0
        && router.count(
            "if (fireAction !is null) fireAction(btn.action);") == 1
        && identifierCount(router, "ActionMenuActions") == 0
        && identifierCount(router, "ActionMenuRead") == 0,
        "6560 input-router boundary: pie dispatch must remain a guarded delegate");

    size_t sourceFiles;
    size_t oldDispatches;
    size_t oldActionSignatures;
    foreach (entry; dirEntries(repoRoot.buildPath("source"), "*.d",
                               SpanMode.depth)) {
        ++sourceFiles;
        const source = blankNonCode(readText(entry.name));
        oldDispatches += source.count("dispatchAction(EditorApp");
        oldActionSignatures += source.count("(EditorApp app, ref Action");
    }
    assert(sourceFiles > 550,
        "6560 source sweep floor: fewer than 551 D source files were scanned");
    assert(oldDispatches == 0 && oldActionSignatures == 0,
        "6560 source sweep: a whole-app action dispatch signature remains");

    const flatApp = collapseWhitespace(app);
    assert(flatApp.count("import ui.action_menu : bindActionMenu;") == 1
        && flatApp.count("import ui.availability : actionRefusal;") == 1
        && flatApp.count(
            "auto actionMenuRoles = bindActionMenu((ref const Action a) => actionRefusal(reg, a, document.hasEditTarget(), activeToolId), uiCommandDelegate, cast(void delegate(string))&activateToolById, cast(bool delegate(string))&tryOpenArgsDialog);") == 1
        && flatApp.count(
            "router.fireAction = (ref Action a) => dispatchAction(actionMenuRoles.actions, a);") == 1
        && flatApp.count("drawSidePanel(app, actionMenuRoles);") == 1
        && flatApp.count("drawStatusBar(app, actionMenuRoles);") == 1,
        "6560 app wiring: the binder, delegate, or panel consumers changed");
    const uiDelegateAt = app.indexOf(
        "uiCommandDelegate = (string id, string paramsJson) {");
    const bindAt = app.indexOf("auto actionMenuRoles = bindActionMenu(");
    const routerAssignAt = app.indexOf("router.fireAction =");
    enum frameMarker = "void frame() {";
    assert(app.count(frameMarker) == 1,
        "6560 app frame anchor must occur exactly once");
    const frameAt = app.indexOf(frameMarker);
    const frameBody = bodyAt(app, frameMarker);
    const sideDrawAt = frameBody.indexOf("drawSidePanel(app, actionMenuRoles);");
    const statusDrawAt = frameBody.indexOf("drawStatusBar(app, actionMenuRoles);");
    assert(uiDelegateAt >= 0 && uiDelegateAt < bindAt
        && bindAt < routerAssignAt && routerAssignAt < frameAt
        && sideDrawAt >= 0 && sideDrawAt < statusDrawAt,
        "6560 app wiring order: bind and router assignment must precede the frame consumers");
    assert(panels.count("tryOpenArgsDialog") == 0,
        "6560 args policy: panels.d regained a second args-dialog door");
}

// Task 7111 (S1-R, item V19): the panel's Undo/Redo rows must enter through
// the same session-aware navigator as Ctrl+Z, so `runCommandRow` has to peel
// `history.undo` / `history.redo` off BEFORE the args-dialog and command
// doors. A text census of the production body: literal occurrences are found
// in the raw text at offsets that both blanked projections (code view:
// literals+comments blank; marker view: literals blank, comments kept) show
// as blank — i.e. inside a string literal, not in a comment. Red on HEAD by
// design (the red half of a red/green pair); kept LAST in the module so every
// cell above runs first.
private size_t[] literalOffsets(string raw, string needle) {
    import tests.unit.census_symbols : blankNonCode;
    const code = blankNonCode(raw);
    const marked = blankNonCode(raw, true);
    size_t[] at;
    for (size_t i = 0; i + needle.length <= raw.length; ++i) {
        if (raw[i .. i + needle.length] != needle) continue;
        bool literal = true;
        foreach (k; i .. i + needle.length)
            if (code[k] != ' ' || marked[k] != ' ') { literal = false; break; }
        if (literal) at ~= i;
    }
    return at;
}

private size_t[] identOffsets(string code, string ident) {
    size_t[] at;
    for (ptrdiff_t from = 0;;) {
        const i = code[cast(size_t)from .. $].indexOf(ident);
        if (i < 0) break;
        const p = cast(size_t)(from + i);
        const before = p == 0 ? ' ' : code[p - 1];
        const after = p + ident.length < code.length ? code[p + ident.length] : ' ';
        if (!identifierChar(before) && !identifierChar(after)) at ~= p;
        from = cast(ptrdiff_t)(p + ident.length);
    }
    return at;
}

unittest { // 7111 V19: panel history rows route through navHistory
    import std.conv : to;
    import tests.unit.census_symbols : blankNonCode;
    // Positive control of the detector: one literal counted, the comment
    // spelling of the same text not counted.
    enum probe = "void f(string id) {\n    // \"history.undo\" named in a comment\n"
        ~ "    if (id == \"history.undo\") { nav_(true); return; }\n}\n";
    assert(literalOffsets(probe, `"history.undo"`).length == 1,
        "7111 V19 detector control: a literal in code must count once, a comment not at all");

    const raw = readText(repoRoot.buildPath("source", "ui", "action_menu.d"));
    const code = blankNonCode(raw);
    const bodyText = bodyAt(code, "void runCommandRow(");
    const b = cast(size_t)(bodyText.ptr - code.ptr);
    const e = b + bodyText.length;
    const openArgs = identOffsets(bodyText, "openArgs_");
    const dispatch = identOffsets(bodyText, "dispatch_");
    // POPULATION FLOOR: the two doors the navigation branch must precede.
    assert(openArgs.length >= 1 && dispatch.length >= 1,
        "7111 V19 census floor: runCommandRow no longer names openArgs_ and dispatch_");
    const firstDoor = b + (openArgs[0] < dispatch[0] ? openArgs[0] : dispatch[0]);
    size_t[] inBody(size_t[] offs) {
        size_t[] r;
        foreach (o; offs) if (o >= b && o < e) r ~= o;
        return r;
    }
    const undo = inBody(literalOffsets(raw, `"history.undo"`));
    const redo = inBody(literalOffsets(raw, `"history.redo"`));
    // Every spelling of each literal must sit ahead of the first door (>= 1
    // each: a split undo/redo branch is legal), and the navigator door
    // `nav_` must be NAMED between the first literal and that door — an
    // empty branch that falls through to the doors has the literals in
    // place and must still redden (reviewer mutation R-M2, task 7112).
    bool allAhead(const size_t[] offs) {
        foreach (o; offs) if (o >= firstDoor) return false;
        return true;
    }
    const ahead = undo.length >= 1 && redo.length >= 1
        && allAhead(undo) && allAhead(redo);
    assert(ahead,
        "panel history.undo bypasses navHistory: runCommandRow has "
        ~ undo.length.to!string ~ " \"history.undo\" and " ~ redo.length.to!string
        ~ " \"history.redo\" literal(s), expected at least 1 and 1, all ahead of its "
        ~ "openArgs_/dispatch_ doors");
    const firstLiteral = undo[0] < redo[0] ? undo[0] : redo[0];
    bool navBetween = false;
    foreach (o; identOffsets(bodyText, "nav_"))
        if (b + o > firstLiteral && b + o < firstDoor) { navBetween = true; break; }
    assert(navBetween,
        "panel history.undo bypasses navHistory: runCommandRow names no nav_ door "
        ~ "between its first history literal and its openArgs_/dispatch_ doors");
}
