tools:
  move:   W
  rotate: E
  scale:  R
  prim.cube: ""
  bevel:  B

commands:
  select.expand:         "Shift+Up"
  select.contract:       "Shift+Down"
  select.more:           Up
  select.less:           Down
  select.loop:           L
  select.ring:           "Alt+L"
  select.invert:         "["
  select.connect:        "]"
  select.between:        "Shift+G"
  viewport.fit:          A
  viewport.fit_selected: "Shift+A"
  mesh.subdivide:        "D"
  history.undo:          "Ctrl+Z"
  history.redo:          "Ctrl+Shift+Z"
  mesh.delete:           Delete
  mesh.remove:           Backspace
  snap.toggle:           X
  file.new:              "Ctrl+N"
  file.load:             "Ctrl+O"
  file.save:             "Ctrl+S"
  file.quit:             "Ctrl+Q"

editmodes:
  vertices: "1"
  edges:    "2"
  polygons: "3"
